### ISSUE TITLE
Ability to Customize Labels for StandardFacets Component

### ISSUE THREAD

**Issue by baigel1** [yext/search-ui-react#352]
#### Description
More and more users are asking us how to customize labels on their facets/filters. At the moment, we don’t have a way to do this, yet it’s a feature I think more and more people will want to use. The default label name uses the field display value from the KG, which I think is a good default value, but we should allow users to change it as the display value can often be confusing.

For example, label names often come from linked entities or values like “price.value”, and seeing a label name of price.value is a strange end-user experience.

#### Screenshots
![facets](https://user-images.githubusercontent.com/99203129/218860590-6688c2ef-40a2-412c-86c7-d482e625a212.png)

#### Files
The main component this enhancement would improve would be the StandardFacets component, which you can find at the following path: yext/search-ui-react/src/components/StandardFacets.tsx (https://github.com/yext/search-ui-react/blob/main/src/components/StandardFacets.tsx)

#### Methods
The main way we have discussed adding this functionality is by introducing decorated actions, so that when a particular function is run e.g. executeFilterSearch, we can intercept the function call and edit the data with the desired label names.
Another idea would be to add a new prop that allows the end user to override the default label names.

**Comment by tmeyer2115** [comment]
We have an Epic which will support this feature: https://yexttest.atlassian.net/browse/PB-16819. It's broken down, but not yet scheduled.

**Comment by apav-dev** [comment]
We discussed an alternative to decorating search actions to handle customization of the Facets component in [this thread](https://yext.slack.com/archives/C016ZKY42CF/p1675952469157189). 

In summary, the product team agrees that we only want to change the appearance of this particular component without caring about the broader state/actions of the application.

I put together [this video](https://www.loom.com/share/1dbd9031b5394a4eb714e3b3191d3b9b) and [code sample](https://www.loom.com/share/1dbd9031b5394a4eb714e3b3191d3b9b) that shows a prototype of what Facets could look like as a compound component.

**Comment by baigel1** [comment]
We have made significant improvements to our Facets components as of version 1.3 of search-ui-react. These improvements include updating the labels of individual facets, so going to close this issue!
