### ISSUE TITLE
SearchBar autocomplete dropdown text alignment and icon size issue

### ISSUE THREAD

**Issue by apav-dev** [yext/search-ui-react#353]
In my project, I am using the SearchBar component and its default autocomplete functionality. As you can see from the attached image, when the autocomplete result is longer than a certain length and part of the result is matched by the query string, the text on the 2nd line of the result does not left align like the first line does. The magnifying glass icon is also a different size than the results that take up one line.

<img width="350" alt="image" src="https://user-images.githubusercontent.com/72618502/221449735-ff0f6221-873e-48e5-9055-9fc526336211.png">

I believe this is an issue with the behavior of the underlying `renderHighlightedValue` function that is utilized by the autocomplete dropdown component.

**Comment by baigel1** [comment]
Hey @apav-dev,

This issue has been fixed as of search-ui-react version 1.3!

Thanks for bringing it to our attention.
