### ISSUE TITLE
Support React 18

### ISSUE THREAD

**Issue by chrissnyder2337** [yext/search-ui-react#420]
This project currently supports React 16 and 17. React 18 was released on 29 Mar 2022. 

Support for React 18 would allow using these Search UI components in projects built using React 18. Many projects started within the past year and a half are most likely using React 18 and can not take advantage of this library.

**Comment by benmcginnis** [comment]
Hi @chrissnyder2337, we'll be actively working on this shortly!  There were some dependencies in our dependency chain that were going to make providing support for 16, 17, and 18 annoying, but we think we have a plan and will be working on it in the next few weeks.

**Comment by mike-potter** [comment]
Any update status on this? We have a client project that really needs the React 18 version.

**Comment by benmcginnis** [comment]
Actively working on it in #423

**Comment by chrissnyder2337** [comment]
It looks like this was fixed by #423, closing.
